### ISSUE TITLE
Include Bootstrap CSS

### ISSUE THREAD

**Issue by danjso** [the-team-random/mgt656-spring-2015-project#5]
The Bootstrap CSS should be included using a link element in the head with an href attribute that has the word "bootstrap" in it, like "bootstrap.css" or "bootstrap-min.css"

**Comment by kalanirosell** [comment]
This has been completed already

**Comment by danjso** [comment]
This is a test dude, still learning how to use it.

**Comment by kalanirosell** [comment]
Got it. My bad.

**Comment by danjso** [comment]
No worries! I'll put all assignments and only after I'll assign people, didn't know it sends emails automatically...
